#ifndef ANALYZEMFT_VERSION_H
#define ANALYZEMFT_VERSION_H

#define ANALYZEMFT_VERSION_MAJOR 1
#define ANALYZEMFT_VERSION_MINOR 0
#define ANALYZEMFT_VERSION_PATCH 1
#define ANALYZEMFT_VERSION_BUILD 1
#define ANALYZEMFT_VERSION_STRING "1.0.1.1"

#endif